# Ansible Inventory Template
# Generated by Terraform

[webservers]
%{ for name, config in servers ~}
%{ if config.role == "webserver" ~}
${name} ansible_host=${config.ip_address} ansible_user=ubuntu server_role=${config.role} server_os=${config.os}
%{ endif ~}
%{ endfor ~}

[databases]
%{ for name, config in servers ~}
%{ if config.role == "database" ~}
${name} ansible_host=${config.ip_address} ansible_user=ubuntu server_role=${config.role} server_os=${config.os}
%{ endif ~}
%{ endfor ~}

[applications]
%{ for name, config in servers ~}
%{ if config.role == "application" ~}
${name} ansible_host=${config.ip_address} ansible_user=ubuntu server_role=${config.role} server_os=${config.os}
%{ endif ~}
%{ endfor ~}

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3