# My First Terraform Module
# This module creates a simple application configuration

# ========================================================================
# MODULE RESOURCES
# ========================================================================

# Create the main application configuration file
resource "local_file" "app_config" {
  filename = var.output_path != "" ? "${var.output_path}/${var.app_name}-config.json" : "${path.module}/output/${var.app_name}-config.json"
  
  content = jsonencode({
    application = {
      name        = var.app_name
      version     = var.app_version
      environment = var.environment
      port        = var.port
    }
    
    features = var.features
    
    database = {
      enabled  = var.database_enabled
      type     = var.database_type
      host     = var.database_enabled ? "${var.app_name}-db.${var.environment}.local" : null
      port     = var.database_enabled ? 5432 : null
    }
    
    metadata = merge(var.tags, {
      created_by = "terraform-module"
      created_at = timestamp()
      module_version = var.module_version
    })
  })
}

# Create environment-specific configuration
resource "local_file" "env_config" {
  filename = var.output_path != "" ? "${var.output_path}/${var.environment}.env" : "${path.module}/output/${var.environment}.env"
  
  content = <<-EOT
    # Environment Configuration for ${var.app_name}
    # Generated by Terraform Module
    
    APP_NAME=${var.app_name}
    APP_VERSION=${var.app_version}
    APP_PORT=${var.port}
    ENVIRONMENT=${var.environment}
    
    # Feature Flags
    %{ for feature, enabled in var.features ~}
    FEATURE_${upper(feature)}=${enabled}
    %{ endfor ~}
    
    # Database Configuration
    DB_ENABLED=${var.database_enabled}
    %{ if var.database_enabled ~}
    DB_TYPE=${var.database_type}
    DB_HOST=${var.app_name}-db.${var.environment}.local
    DB_PORT=5432
    %{ endif ~}
  EOT
}

# Create a README for the application
resource "local_file" "readme" {
  count = var.create_readme ? 1 : 0
  
  filename = var.output_path != "" ? "${var.output_path}/README.md" : "${path.module}/output/README.md"
  
  content = <<-EOT
    # ${var.app_name}
    
    ## Application Information
    - **Name**: ${var.app_name}
    - **Version**: ${var.app_version}
    - **Environment**: ${var.environment}
    - **Port**: ${var.port}
    
    ## Features
    %{ for feature, enabled in var.features ~}
    - ${feature}: ${enabled ? "✓ Enabled" : "✗ Disabled"}
    %{ endfor ~}
    
    ## Database
    - **Enabled**: ${var.database_enabled ? "Yes" : "No"}
    %{ if var.database_enabled ~}
    - **Type**: ${var.database_type}
    - **Host**: ${var.app_name}-db.${var.environment}.local
    - **Port**: 5432
    %{ endif ~}
    
    ## Deployment
    This configuration was generated by a Terraform module.
    
    ### Module Version
    ${var.module_version}
    
    ### Tags
    %{ for key, value in var.tags ~}
    - ${key}: ${value}
    %{ endfor ~}
    
    ---
    Generated at: ${timestamp()}
  EOT
}

# Local values for computed data
locals {
  # Construct the full application identifier
  app_identifier = "${var.app_name}-${var.environment}-${var.app_version}"
  
  # Determine which features are enabled
  enabled_features = [
    for feature, enabled in var.features : feature if enabled
  ]
  
  # Create connection string if database is enabled
  connection_string = var.database_enabled ? (
    "${var.database_type}://${var.app_name}-db.${var.environment}.local:5432/${var.app_name}"
  ) : null
  
  # Calculate total configuration items
  config_count = 2 + (var.create_readme ? 1 : 0)
}