#!/bin/bash
# Web server user data script
# Configures nginx web server with application monitoring

# Set hostname
hostnamectl set-hostname "${hostname}"

# Update system
apt-get update

# Install web server packages
apt-get install -y \
    curl \
    wget \
    vim \
    htop \
    git \
    nginx \
    php-fpm \
    php-mysql \
    php-curl \
    php-json \
    mysql-client \
    python3 \
    python3-pip \
    nodejs \
    npm

# Configure nginx
systemctl enable nginx
systemctl start nginx

# Install Node.js application dependencies
npm install -g pm2

# Create web application
cat > /var/www/html/index.html << EOF
<!DOCTYPE html>
<html>
<head>
    <title>Web Server ${server_id} - Load Balanced Application</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 40px; 
            background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%);
            color: white;
        }
        .container { 
            background: rgba(255,255,255,0.1); 
            padding: 30px; 
            border-radius: 10px; 
            backdrop-filter: blur(10px);
        }
        .server-badge { 
            background: #27ae60; 
            padding: 10px 20px; 
            border-radius: 25px; 
            display: inline-block; 
            margin: 10px 0;
            font-weight: bold;
        }
        .status { color: #27ae60; }
        .info { background: rgba(255,255,255,0.1); padding: 15px; border-radius: 5px; margin: 15px 0; }
        pre { background: rgba(0,0,0,0.3); padding: 15px; border-radius: 5px; overflow-x: auto; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .metric { text-align: center; padding: 20px; background: rgba(255,255,255,0.1); border-radius: 10px; }
        .metric h3 { margin: 0; color: #f39c12; }
        .metric .value { font-size: 2em; margin: 10px 0; }
    </style>
    <script>
        function updateStats() {
            fetch('/api/stats')
                .then(response => response.json())
                .then(data => {
                    document.getElementById('cpu-usage').textContent = data.cpu + '%';
                    document.getElementById('memory-usage').textContent = data.memory + '%';
                    document.getElementById('disk-usage').textContent = data.disk + '%';
                    document.getElementById('uptime').textContent = data.uptime;
                    document.getElementById('requests').textContent = data.requests;
                })
                .catch(() => console.log('Stats not available'));
        }
        
        setInterval(updateStats, 5000);
        window.onload = updateStats;
    </script>
</head>
<body>
    <div class="container">
        <h1>🌐 Web Server ${server_id}</h1>
        <div class="server-badge">SERVER ID: ${server_id}</div>
        <p class="status">✅ Load-balanced web application is running</p>
        
        <div class="info">
            <h3>🏷️ Server Information</h3>
            <p><strong>Hostname:</strong> ${hostname}</p>
            <p><strong>Server ID:</strong> ${server_id}</p>
            <p><strong>Role:</strong> Frontend Web Server</p>
            <p><strong>Load Balancer Member:</strong> Yes</p>
        </div>
        
        <div class="grid">
            <div class="metric">
                <h3>CPU Usage</h3>
                <div class="value" id="cpu-usage">--</div>
            </div>
            <div class="metric">
                <h3>Memory Usage</h3>
                <div class="value" id="memory-usage">--</div>
            </div>
            <div class="metric">
                <h3>Disk Usage</h3>
                <div class="value" id="disk-usage">--</div>
            </div>
            <div class="metric">
                <h3>Uptime</h3>
                <div class="value" id="uptime">--</div>
            </div>
        </div>
        
        <div class="info">
            <h3>🔗 Database Connectivity</h3>
            <div id="db-status">
                <p>Testing connections to database servers...</p>
                <ul id="db-list"></ul>
            </div>
        </div>
        
        <div class="info">
            <h3>📊 Application Metrics</h3>
            <p>Total Requests Served: <span id="requests">--</span></p>
            <p>Response Time: <span id="response-time">< 50ms</span></p>
            <p>Status: <span class="status">Healthy</span></p>
        </div>
        
        <div class="info">
            <h3>🎯 Load Balancer Test</h3>
            <p>Refresh this page multiple times to see different servers respond.</p>
            <p>Each server has a unique ID and color scheme for identification.</p>
        </div>
        
        <p><em>Generated by Web Server ${server_id} at $(date)</em></p>
    </div>
    
    <script>
        // Test database connectivity
        const dbServers = '${db_servers}'.split(',');
        const dbList = document.getElementById('db-list');
        
        dbServers.forEach((server, index) => {
            if (server.trim()) {
                const li = document.createElement('li');
                li.innerHTML = \`DB Server \${index + 1} (\${server}): <span style="color: #f39c12">Testing...</span>\`;
                dbList.appendChild(li);
                
                // Test database connectivity (simulated)
                setTimeout(() => {
                    li.innerHTML = \`DB Server \${index + 1} (\${server}): <span style="color: #27ae60">Connected</span>\`;
                }, 2000 + index * 500);
            }
        });
    </script>
</body>
</html>
EOF

# Create API endpoint for stats
mkdir -p /var/www/html/api

cat > /var/www/html/api/stats << 'EOF'
#!/bin/bash
echo "Content-Type: application/json"
echo ""

# Get system stats
cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'%' -f1)
memory_usage=$(free | grep Mem | awk '{printf "%.1f", $3/$2 * 100.0}')
disk_usage=$(df / | tail -1 | awk '{print $5}' | cut -d'%' -f1)
uptime=$(uptime -p)
requests=$(wc -l < /var/log/nginx/access.log 2>/dev/null || echo "0")

cat << END
{
  "cpu": "${cpu_usage:-0}",
  "memory": "${memory_usage:-0}",
  "disk": "${disk_usage:-0}",
  "uptime": "${uptime}",
  "requests": "${requests}",
  "server_id": "${server_id}",
  "timestamp": "$(date -Iseconds)"
}
END
EOF

chmod +x /var/www/html/api/stats

# Create health check endpoint
cat > /var/www/html/health << 'EOF'
#!/bin/bash
echo "Content-Type: application/json"
echo ""

# Basic health checks
nginx_status=$(systemctl is-active nginx)
disk_space=$(df / | tail -1 | awk '{print $4}')
load_avg=$(cat /proc/loadavg | cut -d' ' -f1)

if [ "$nginx_status" = "active" ] && [ "$disk_space" -gt 1000000 ]; then
    status="healthy"
    code=200
else
    status="unhealthy"
    code=503
fi

cat << END
{
  "status": "$status",
  "server_id": "${server_id}",
  "nginx": "$nginx_status",
  "disk_free_kb": "$disk_space",
  "load_average": "$load_avg",
  "timestamp": "$(date -Iseconds)"
}
END
EOF

chmod +x /var/www/html/health

# Configure nginx with PHP and API endpoints
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html index.php;
    
    server_name _;
    
    # Add server identification header
    add_header X-Server-ID "${server_id}" always;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    # API endpoints
    location ~ ^/(api/stats|health)$ {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    
    # PHP processing
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
    }
    
    # Security headers
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
}
EOF

# Install and configure fcgiwrap
apt-get install -y fcgiwrap
systemctl enable fcgiwrap
systemctl start fcgiwrap

# Configure PHP-FPM
systemctl enable php8.1-fpm
systemctl start php8.1-fpm

# Create a simple PHP info page
cat > /var/www/html/info.php << 'EOF'
<?php
echo "<h1>Web Server ${server_id} - PHP Info</h1>";
echo "<p>Server ID: ${server_id}</p>";
echo "<p>Hostname: " . gethostname() . "</p>";
echo "<p>Server IP: " . $_SERVER['SERVER_ADDR'] . "</p>";
echo "<p>Request Time: " . date('Y-m-d H:i:s') . "</p>";

// Database connection test
$db_servers = explode(',', '${db_servers}');
echo "<h2>Database Connectivity</h2>";
foreach ($db_servers as $index => $db_server) {
    $db_server = trim($db_server);
    if ($db_server) {
        echo "<p>DB Server " . ($index + 1) . " ($db_server): ";
        $connection = @fsockopen($db_server, 3306, $errno, $errstr, 3);
        if ($connection) {
            echo "<span style='color: green'>MySQL Port Open</span>";
            fclose($connection);
        } else {
            echo "<span style='color: red'>Connection Failed</span>";
        }
        echo "</p>";
    }
}

phpinfo();
?>
EOF

# Set proper permissions
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
chmod +x /var/www/html/api/stats /var/www/html/health

# Restart services
systemctl restart nginx
systemctl restart php8.1-fpm

# Configure log rotation
cat > /etc/logrotate.d/webapp << 'EOF'
/var/log/nginx/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0644 www-data adm
    sharedscripts
    prerotate
        if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
            run-parts /etc/logrotate.d/httpd-prerotate; \
        fi
    endscript
    postrotate
        systemctl reload nginx
    endscript
}
EOF

# Create startup script for application monitoring
cat > /opt/web-monitor.sh << 'EOF'
#!/bin/bash
# Web application monitoring script

while true; do
    # Check nginx status
    if ! systemctl is-active --quiet nginx; then
        echo "$(date): Nginx down, restarting..." >> /var/log/web-monitor.log
        systemctl restart nginx
    fi
    
    # Check disk space
    disk_usage=$(df / | tail -1 | awk '{print $5}' | cut -d'%' -f1)
    if [ "$disk_usage" -gt 90 ]; then
        echo "$(date): Disk usage high: ${disk_usage}%" >> /var/log/web-monitor.log
    fi
    
    sleep 60
done
EOF

chmod +x /opt/web-monitor.sh

# Start monitoring in background
nohup /opt/web-monitor.sh > /dev/null 2>&1 &

# Create MOTD
cat > /etc/motd << EOF

  ╔══════════════════════════════════════════════════════════════════╗
  ║   🌐 WEB SERVER ${server_id} - LOAD BALANCED APPLICATION          ║
  ║                                                                  ║
  ║   This server is part of a load-balanced web application        ║
  ║   deployed with Terraform on OpenStack.                         ║
  ║                                                                  ║
  ║   Services:                                                      ║
  ║   • Nginx Web Server (Port 80)                                  ║
  ║   • PHP-FPM Application Server                                  ║
  ║   • Health Check Endpoints                                      ║
  ║   • Application Metrics API                                     ║
  ║                                                                  ║
  ║   URLs:                                                          ║
  ║   • Application: http://[server-ip]/                            ║
  ║   • Health Check: http://[server-ip]/health                     ║
  ║   • Stats API: http://[server-ip]/api/stats                     ║
  ║   • PHP Info: http://[server-ip]/info.php                       ║
  ╚══════════════════════════════════════════════════════════════════╝

EOF

# Log completion
echo "$(date): Web server ${server_id} configuration completed" >> /var/log/terraform-init.log
touch /var/lib/cloud/web-init-complete