#!/bin/bash
# User data script for OpenStack VM initialization
# This script runs when the VM first boots

# Set hostname
hostnamectl set-hostname "${hostname}"

# Update system packages
apt-get update

# Install essential packages
apt-get install -y \
    curl \
    wget \
    vim \
    htop \
    git \
    nginx \
    python3 \
    python3-pip

# Configure nginx
systemctl enable nginx
systemctl start nginx

# Create a simple welcome page
cat > /var/www/html/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>OpenStack VM - Deployed with Terraform</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 40px; 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .container { 
            background: rgba(255,255,255,0.1); 
            padding: 30px; 
            border-radius: 10px; 
            backdrop-filter: blur(10px);
        }
        .status { color: #90EE90; }
        .info { background: rgba(255,255,255,0.1); padding: 10px; border-radius: 5px; margin: 10px 0; }
        pre { background: rgba(0,0,0,0.3); padding: 10px; border-radius: 5px; overflow-x: auto; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 OpenStack VM Successfully Deployed!</h1>
        <p class="status">✅ Virtual Machine is running and accessible</p>
        
        <div class="info">
            <h3>🏷️ Instance Information</h3>
            <p><strong>Hostname:</strong> ${hostname}</p>
            <p><strong>Deployed with:</strong> Terraform + OpenStack</p>
            <p><strong>Image:</strong> Ubuntu 22.04 LTS</p>
            <p><strong>Web Server:</strong> Nginx</p>
        </div>
        
        <div class="info">
            <h3>🔧 Available Services</h3>
            <ul>
                <li>SSH Server (Port 22)</li>
                <li>HTTP Web Server (Port 80)</li>
                <li>HTTPS Ready (Port 443)</li>
                <li>ICMP/Ping Enabled</li>
            </ul>
        </div>
        
        <div class="info">
            <h3>📋 System Status</h3>
            <pre id="system-info">Loading system information...</pre>
        </div>
        
        <div class="info">
            <h3>🌐 Network Information</h3>
            <pre id="network-info">Loading network information...</pre>
        </div>
        
        <p><em>This page was generated by the user-data script during VM initialization.</em></p>
    </div>
    
    <script>
        // Load system information
        fetch('/system-info')
            .then(response => response.text())
            .then(data => document.getElementById('system-info').textContent = data)
            .catch(() => document.getElementById('system-info').textContent = 'System info endpoint not available');
            
        // Load network information
        fetch('/network-info')
            .then(response => response.text())
            .then(data => document.getElementById('network-info').textContent = data)
            .catch(() => document.getElementById('network-info').textContent = 'Network info endpoint not available');
    </script>
</body>
</html>
EOF

# Create system info endpoint
cat > /var/www/html/system-info << 'EOF'
#!/bin/bash
echo "Content-Type: text/plain"
echo ""
echo "=== SYSTEM INFORMATION ==="
echo "Hostname: $(hostname)"
echo "Uptime: $(uptime)"
echo "Memory: $(free -h | grep Mem | awk '{print $3 "/" $2}')"
echo "Disk: $(df -h / | tail -1 | awk '{print $3 "/" $2 " (" $5 " used)"}')"
echo "Load: $(cat /proc/loadavg | cut -d' ' -f1-3)"
echo "Processes: $(ps aux | wc -l)"
echo "Last boot: $(who -b | awk '{print $3, $4}')"
EOF

chmod +x /var/www/html/system-info

# Create network info endpoint  
cat > /var/www/html/network-info << 'EOF'
#!/bin/bash
echo "Content-Type: text/plain"
echo ""
echo "=== NETWORK INFORMATION ==="
echo "Interfaces:"
ip addr show | grep -E '^[0-9]+:|inet ' | sed 's/^/  /'
echo ""
echo "Routing table:"
ip route show | sed 's/^/  /'
echo ""
echo "DNS servers:"
cat /etc/resolv.conf | grep nameserver | sed 's/^/  /'
EOF

chmod +x /var/www/html/network-info

# Configure nginx to serve scripts as CGI
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html;
    
    server_name _;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    location ~ ^/(system-info|network-info)$ {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
EOF

# Install and configure fcgiwrap for CGI scripts
apt-get install -y fcgiwrap
systemctl enable fcgiwrap
systemctl start fcgiwrap

# Restart nginx to apply configuration
systemctl restart nginx

# Create a motd banner
cat > /etc/motd << 'EOF'

  ╔══════════════════════════════════════════════════════════════════╗
  ║   🚀 OpenStack VM - Deployed with Terraform                     ║
  ║                                                                  ║
  ║   This virtual machine was created using:                       ║
  ║   • Terraform Infrastructure as Code                            ║
  ║   • OpenStack Cloud Platform                                    ║
  ║   • Automated configuration with user-data                      ║
  ║                                                                  ║
  ║   Services running:                                              ║
  ║   • SSH (Port 22)                                               ║
  ║   • HTTP Web Server (Port 80)                                   ║
  ║   • System monitoring endpoints                                  ║
  ║                                                                  ║
  ║   Try: curl localhost/system-info                                ║
  ║        curl localhost/network-info                               ║
  ╚══════════════════════════════════════════════════════════════════╝

EOF

# Log successful completion
echo "$(date): User data script completed successfully" >> /var/log/terraform-init.log

# Create a flag file to indicate completion
touch /var/lib/cloud/terraform-init-complete