# ╔════════════════════════════════════════════════════════════════════╗
# ║  DOCKER COMPOSE INTEGRATION                                     ║
# ║  Terraform vs Docker Compose: patterns and migration             ║
# ╚════════════════════════════════════════════════════════════════════╝

# Docker Compose and Terraform both manage multi-container environments,
# but serve different purposes. This exercise explores when to use each,
# how they complement each other, and migration patterns for teams
# moving from Compose to Terraform-managed infrastructure.

# POWERSHELL COMPARISON:
# =====================
# Like the difference between a PowerShell script and a DSC config:
#   Script: docker-compose up -d  (run this sequence)
#   DSC:    resource "docker_container" (ensure this state exists)
# Compose is imperative sequencing, Terraform is declarative state.

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
  required_version = ">= 1.0"
}

# ========================================================================
# VARIABLES
# ========================================================================

variable "project_name" {
  description = "Project name for container naming"
  type        = string
  default     = "myapp"
}

variable "environment" {
  description = "Environment"
  type        = string
  default     = "dev"
}

variable "services" {
  description = "Application services to deploy"
  type = map(object({
    image    = string
    port     = number
    replicas = number
  }))
  default = {
    web = {
      image    = "nginx:alpine"
      port     = 80
      replicas = 2
    }
    api = {
      image    = "node:18-alpine"
      port     = 3000
      replicas = 1
    }
    db = {
      image    = "postgres:15"
      port     = 5432
      replicas = 1
    }
    cache = {
      image    = "redis:7-alpine"
      port     = 6379
      replicas = 1
    }
  }
}

# ========================================================================
# SECTION 1: DOCKER COMPOSE FILE GENERATION
# ========================================================================

resource "local_file" "docker_compose" {
  filename = "./terraform-lab-output/docker-compose/docker-compose.yml"
  content  = <<-EOT
    # Generated by Terraform - Docker Compose for local development
    # Usage: docker-compose up -d

    version: "3.8"

    services:
      web:
        image: ${var.services.web.image}
        ports:
          - "${var.services.web.port}:80"
        depends_on:
          - api
        networks:
          - frontend
          - backend
        deploy:
          replicas: ${var.services.web.replicas}
        restart: unless-stopped

      api:
        image: ${var.services.api.image}
        ports:
          - "${var.services.api.port}:3000"
        environment:
          - DATABASE_URL=postgresql://app:secret@db:5432/${var.project_name}
          - REDIS_URL=redis://cache:6379
        depends_on:
          - db
          - cache
        networks:
          - backend
        restart: unless-stopped

      db:
        image: ${var.services.db.image}
        ports:
          - "${var.services.db.port}:5432"
        environment:
          - POSTGRES_DB=${var.project_name}
          - POSTGRES_USER=app
          - POSTGRES_PASSWORD=secret
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - backend
        restart: unless-stopped

      cache:
        image: ${var.services.cache.image}
        ports:
          - "${var.services.cache.port}:6379"
        networks:
          - backend
        restart: unless-stopped

    networks:
      frontend:
        driver: bridge
      backend:
        driver: bridge

    volumes:
      postgres_data:
        driver: local
  EOT
}

# ========================================================================
# SECTION 2: TERRAFORM EQUIVALENT
# ========================================================================

resource "local_file" "terraform_equivalent" {
  filename = "./terraform-lab-output/docker-compose/terraform-docker-equivalent.tf"
  content  = <<-EOT
    # ============================================
    # SAME STACK IN TERRAFORM (Docker Provider)
    # ============================================
    # This is the Terraform equivalent of the docker-compose.yml above

    terraform {
      required_providers {
        docker = {
          source  = "kreuzwerker/docker"
          version = "~> 3.0"
        }
      }
    }

    provider "docker" {}

    # --- Networks ---
    resource "docker_network" "frontend" {
      name = "${var.project_name}-frontend"
    }

    resource "docker_network" "backend" {
      name = "${var.project_name}-backend"
    }

    # --- Volumes ---
    resource "docker_volume" "postgres_data" {
      name = "${var.project_name}-postgres-data"
    }

    # --- Database ---
    resource "docker_image" "postgres" {
      name = "${var.services.db.image}"
    }

    resource "docker_container" "db" {
      name  = "${var.project_name}-db"
      image = docker_image.postgres.image_id

      env = [
        "POSTGRES_DB=${var.project_name}",
        "POSTGRES_USER=app",
        "POSTGRES_PASSWORD=secret",
      ]

      ports {
        internal = 5432
        external = ${var.services.db.port}
      }

      volumes {
        volume_name    = docker_volume.postgres_data.name
        container_path = "/var/lib/postgresql/data"
      }

      networks_advanced {
        name = docker_network.backend.id
      }

      restart = "unless-stopped"
    }

    # --- Cache ---
    resource "docker_image" "redis" {
      name = "${var.services.cache.image}"
    }

    resource "docker_container" "cache" {
      name  = "${var.project_name}-cache"
      image = docker_image.redis.image_id

      ports {
        internal = 6379
        external = ${var.services.cache.port}
      }

      networks_advanced {
        name = docker_network.backend.id
      }

      restart = "unless-stopped"
    }

    # --- API ---
    resource "docker_container" "api" {
      name  = "${var.project_name}-api"
      image = "${var.services.api.image}"

      env = [
        "DATABASE_URL=postgresql://app:secret@$${docker_container.db.name}:5432/${var.project_name}",
        "REDIS_URL=redis://$${docker_container.cache.name}:6379",
      ]

      ports {
        internal = 3000
        external = ${var.services.api.port}
      }

      networks_advanced {
        name = docker_network.backend.id
      }

      depends_on = [docker_container.db, docker_container.cache]
      restart    = "unless-stopped"
    }

    # --- Web (with replicas using count) ---
    resource "docker_container" "web" {
      count = ${var.services.web.replicas}
      name  = "${var.project_name}-web-$${count.index}"
      image = "${var.services.web.image}"

      ports {
        internal = 80
        external = ${var.services.web.port} + count.index
      }

      networks_advanced {
        name = docker_network.frontend.id
      }

      networks_advanced {
        name = docker_network.backend.id
      }

      depends_on = [docker_container.api]
      restart    = "unless-stopped"
    }
  EOT
}

# ========================================================================
# SECTION 3: COMPOSE vs TERRAFORM COMPARISON
# ========================================================================

resource "local_file" "comparison" {
  filename = "./terraform-lab-output/docker-compose/compose-vs-terraform.json"
  content = jsonencode({
    title = "Docker Compose vs Terraform: When to Use Each"
    comparison = {
      docker_compose = {
        best_for = [
          "Local development environments",
          "Simple multi-container apps",
          "Quick prototyping and demos",
          "Docker-only workflows"
        ]
        strengths = [
          "Simple YAML syntax",
          "docker-compose up starts everything",
          "Built-in log aggregation",
          "Hot-reload with volume mounts",
          "Wide community support"
        ]
        limitations = [
          "No state tracking between runs",
          "Docker-only (not cloud resources)",
          "Limited health check logic",
          "No plan/preview before changes",
          "Scaling requires Swarm mode"
        ]
      }
      terraform_docker = {
        best_for = [
          "Production container deployments",
          "Hybrid infrastructure (containers + cloud)",
          "When you need state tracking",
          "Complex dependency management"
        ]
        strengths = [
          "State-tracked resources",
          "terraform plan before changes",
          "Can manage cloud + containers together",
          "for_each/count for replicas",
          "Same workflow as all other infrastructure"
        ]
        limitations = [
          "More verbose syntax",
          "No built-in log following",
          "Overkill for simple dev setups",
          "Requires Terraform knowledge"
        ]
      }
    }
    recommendation = {
      local_dev     = "Docker Compose (simpler, faster iteration)"
      staging       = "Either (depends on team preference)"
      production    = "Terraform or Kubernetes (state tracking, cloud integration)"
      migration     = "Start with Compose, graduate to Terraform when you need cloud resources"
    }
  })
}

# ========================================================================
# SECTION 4: POWERSHELL COMPARISON
# ========================================================================

resource "local_file" "powershell_comparison" {
  filename = "./terraform-lab-output/terraform-vs-powershell-docker-compose.ps1"
  content  = <<-EOT
    # Docker Compose: Tools Comparison
    # ==================================

    # DOCKER COMPOSE                   | TERRAFORM (DOCKER)
    # ---------------------------------|-------------------------------
    # docker-compose up -d             | terraform apply
    # docker-compose down              | terraform destroy
    # docker-compose ps                | terraform state list
    # docker-compose logs -f           | docker logs (separate tool)
    # docker-compose scale web=3       | count = 3 in config
    # depends_on: [db]                 | depends_on = [docker_container.db]
    # volumes:                         | docker_volume resource
    # networks:                        | docker_network resource

    # PowerShell Docker management:
    # docker compose up -d
    # docker compose ps | ConvertFrom-Csv
    # docker compose logs api --tail 50
    #
    # # Health check all services
    # (docker compose ps --format json | ConvertFrom-Json) | ForEach-Object {
    #   [PSCustomObject]@{
    #     Service = $$_.Service
    #     State   = $$_.State
    #     Health  = $$_.Health
    #   }
    # } | Format-Table

    Write-Host "Container Orchestration Options:" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  Docker Compose: Local dev, simple stacks" -ForegroundColor Cyan
    Write-Host "  Terraform Docker: State-tracked containers"
    Write-Host "  Kubernetes: Production orchestration"
    Write-Host "  Terraform + K8s: Full lifecycle management"
    Write-Host ""
    Write-Host "  Migration Path:" -ForegroundColor Green
    Write-Host "  Compose -> Terraform Docker -> Terraform + K8s"
    Write-Host "  (Add complexity only when you need it)"
  EOT
}

# ========================================================================
# OUTPUTS
# ========================================================================

output "compose_resources" {
  description = "Generated Docker Compose reference files"
  value = {
    compose_file   = local_file.docker_compose.filename
    terraform_equiv = local_file.terraform_equivalent.filename
    comparison     = local_file.comparison.filename
  }
}

output "lesson_summary" {
  description = "Key takeaways"
  value = {
    compose_best_for  = "Docker Compose is best for local development (simple, fast)"
    terraform_best_for = "Terraform is best when you need state tracking or cloud integration"
    migration_path    = "Start simple with Compose, graduate to Terraform when complexity grows"
    same_concepts     = "Networks, volumes, depends_on all map between Compose and Terraform"
    powershell_tip    = "Use docker compose commands from PowerShell with JSON output for scripting"
    production        = "For production, use Terraform + Kubernetes (not Compose or Docker provider)"
  }
}
